import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface PdfLine {
  type: string;
  name: string;
  quantity: number;
  unit_price: number;
  unit_cost: number;
  vat_rate: number;
}

interface PdfData {
  type: 'quote' | 'service';
  number: string;
  date: string;
  validityDate?: string;
  shopName: string;
  shopEmail: string;
  shopPhone: string;
  shopNif?: string;
  shopAddress?: string;
  shopLogoUrl?: string;
  clientName: string;
  clientEmail?: string;
  clientPhone?: string;
  clientNif?: string;
  vehicleMake: string;
  vehicleModel: string;
  vehiclePlate: string;
  lines: PdfLine[];
  subtotal: number;
  vatTotal: number;
  total: number;
  profit: number;
  notes?: string;
  technician?: string;
  diagnosis?: string;
  laborHours?: number;
  currency: string;
  plan?: 'free' | 'pro' | 'garage';
  language?: string;
}

async function loadImage(url: string): Promise<string | null> {
  try {
    const response = await fetch(url);
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

export async function generatePdf(data: PdfData, watermark: boolean): Promise<jsPDF> {
  const doc = new jsPDF();
  const cur = data.currency === 'EUR' ? '€' : data.currency;
  const pageW = doc.internal.pageSize.getWidth();
  const isFree = watermark || data.plan === 'free';

  // Header bar
  doc.setFillColor(38, 38, 38);
  doc.rect(0, 0, pageW, 40, 'F');

  // Try to load and place shop logo (auto-detect format)
  let logoLoaded = false;
  if (data.shopLogoUrl) {
    const imgData = await loadImage(data.shopLogoUrl);
    if (imgData) {
      const fmt = /^data:image\/(jpe?g|jpg);/i.test(imgData) ? 'JPEG'
        : /^data:image\/webp/i.test(imgData) ? 'WEBP'
        : 'PNG';
      try {
        doc.addImage(imgData, fmt, 14, 6, 28, 28);
        logoLoaded = true;
      } catch {
        // try alternate formats before giving up
        for (const alt of ['PNG', 'JPEG', 'WEBP'].filter(f => f !== fmt)) {
          try { doc.addImage(imgData, alt, 14, 6, 28, 28); logoLoaded = true; break; } catch { /* keep trying */ }
        }
      }
    }
  }

  // Shop info (offset if logo loaded)
  const infoX = logoLoaded ? 48 : 14;
  
  doc.setTextColor(255, 180, 30);
  doc.setFontSize(logoLoaded ? 16 : 22);
  doc.setFont("helvetica", "bold");
  doc.text(data.shopName, infoX, 16);

  doc.setTextColor(180, 180, 180);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  if (data.shopNif) {
    doc.text(`NIF: ${data.shopNif}`, infoX, 22);
  }
  if (data.shopAddress) {
    doc.text(data.shopAddress, infoX, data.shopNif ? 27 : 22);
  }
  doc.text(`${data.shopEmail} | ${data.shopPhone}`, infoX, data.shopNif && data.shopAddress ? 32 : data.shopNif || data.shopAddress ? 27 : 22);

  // i18n labels
  const lang = data.language || 'pt';
  const i18n: Record<string, Record<string, string>> = {
    quote: { pt: 'ORÇAMENTO', en: 'QUOTE', es: 'PRESUPUESTO', 'pt-BR': 'ORÇAMENTO' },
    service: { pt: 'ORDEM DE SERVIÇO', en: 'WORK ORDER', es: 'ORDEN DE SERVICIO', 'pt-BR': 'ORDEM DE SERVIÇO' },
    client: { pt: 'CLIENTE', en: 'CLIENT', es: 'CLIENTE', 'pt-BR': 'CLIENTE' },
    vehicle: { pt: 'VEÍCULO', en: 'VEHICLE', es: 'VEHÍCULO', 'pt-BR': 'VEÍCULO' },
    plate: { pt: 'Matrícula', en: 'Plate', es: 'Matrícula', 'pt-BR': 'Placa' },
    technician: { pt: 'Técnico', en: 'Technician', es: 'Técnico', 'pt-BR': 'Técnico' },
    hours: { pt: 'Horas', en: 'Hours', es: 'Horas', 'pt-BR': 'Horas' },
    validUntil: { pt: 'Válido até', en: 'Valid until', es: 'Válido hasta', 'pt-BR': 'Válido até' },
    date: { pt: 'Data', en: 'Date', es: 'Fecha', 'pt-BR': 'Data' },
    type: { pt: 'Tipo', en: 'Type', es: 'Tipo', 'pt-BR': 'Tipo' },
    description: { pt: 'Descrição', en: 'Description', es: 'Descripción', 'pt-BR': 'Descrição' },
    qty: { pt: 'Qtd', en: 'Qty', es: 'Cant', 'pt-BR': 'Qtd' },
    price: { pt: 'Preço', en: 'Price', es: 'Precio', 'pt-BR': 'Preço' },
    vat: { pt: 'IVA', en: 'VAT', es: 'IVA', 'pt-BR': 'Imposto' },
    total: { pt: 'Total', en: 'Total', es: 'Total', 'pt-BR': 'Total' },
    serviceType: { pt: 'Serviço', en: 'Service', es: 'Servicio', 'pt-BR': 'Serviço' },
    partType: { pt: 'Peça', en: 'Part', es: 'Pieza', 'pt-BR': 'Peça' },
    diagnosis: { pt: 'DIAGNÓSTICO', en: 'DIAGNOSIS', es: 'DIAGNÓSTICO', 'pt-BR': 'DIAGNÓSTICO' },
    notes: { pt: 'NOTAS', en: 'NOTES', es: 'NOTAS', 'pt-BR': 'NOTAS' },
    disclaimer: {
      pt: 'Documento gerado por sistema de gestão. Deve ser comunicado à Autoridade Tributária através de software certificado.',
      en: 'Document generated by management software. Must be reported to the Tax Authority through certified software.',
      es: 'Documento generado por software de gestión. Debe comunicarse a la Autoridad Tributaria mediante software certificado.',
      'pt-BR': 'Documento gerado por sistema de gestão. Consulte a legislação fiscal vigente no seu país.',
    },
  };
  const tl = (key: string) => i18n[key]?.[lang] || i18n[key]?.pt || key;

  // Document type + number
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  const typeLabel = i18n[data.type]?.[lang] || i18n[data.type]?.pt || 'DOCUMENTO';
  doc.text(typeLabel, pageW - 14, 18, { align: "right" });
  doc.setFontSize(11);
  doc.text(data.number, pageW - 14, 26, { align: "right" });
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`${tl('date')}: ${data.date}`, pageW - 14, 34, { align: "right" });

  // Client info
  let y = 50;
  doc.setTextColor(38, 38, 38);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(tl('client'), 14, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  y += 6;
  doc.text(data.clientName, 14, y);
  if (data.clientNif) { y += 5; doc.text(`NIF: ${data.clientNif}`, 14, y); }
  if (data.clientEmail) { y += 5; doc.text(data.clientEmail, 14, y); }
  if (data.clientPhone) { y += 5; doc.text(data.clientPhone, 14, y); }

  // Vehicle info
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text(tl('vehicle'), pageW / 2, 50);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`${data.vehicleMake} ${data.vehicleModel}`, pageW / 2, 56);
  doc.text(`${tl('plate')}: ${data.vehiclePlate}`, pageW / 2, 61);

  if (data.type === 'service') {
    if (data.technician) doc.text(`${tl('technician')}: ${data.technician}`, pageW / 2, 66);
    if (data.laborHours) doc.text(`${tl('hours')}: ${data.laborHours}h`, pageW / 2, 71);
  }

  if (data.validityDate) {
    doc.text(`${tl('validUntil')}: ${data.validityDate}`, pageW / 2, data.type === 'service' ? 76 : 66);
  }

  // Lines table
  const tableY = Math.max(y + 12, 82);
  const tableData = data.lines.map(l => [
    l.type === 'service' ? tl('serviceType') : tl('partType'),
    l.name,
    String(l.quantity),
    `${cur}${l.unit_price.toFixed(2)}`,
    `${l.vat_rate}%`,
    `${cur}${(l.quantity * l.unit_price).toFixed(2)}`,
  ]);

  autoTable(doc, {
    startY: tableY,
    head: [[tl('type'), tl('description'), tl('qty'), tl('price'), tl('vat'), tl('total')]],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [38, 38, 38], textColor: [255, 180, 30], fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 22 },
      2: { cellWidth: 16, halign: 'center' },
      3: { cellWidth: 26, halign: 'right' },
      4: { cellWidth: 16, halign: 'center' },
      5: { cellWidth: 28, halign: 'right' },
    },
    margin: { left: 14, right: 14 },
  });

  // Totals
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  const totalsX = pageW - 14;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(38, 38, 38);
  doc.text(`Subtotal: ${cur}${data.subtotal.toFixed(2)}`, totalsX, finalY, { align: "right" });
  doc.text(`${tl('vat')}: ${cur}${data.vatTotal.toFixed(2)}`, totalsX, finalY + 6, { align: "right" });

  doc.setFillColor(38, 38, 38);
  doc.rect(pageW - 80, finalY + 9, 66, 10, 'F');
  doc.setTextColor(255, 180, 30);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(`TOTAL: ${cur}${data.total.toFixed(2)}`, totalsX, finalY + 16, { align: "right" });

  // Diagnosis
  if (data.type === 'service' && data.diagnosis) {
    doc.setTextColor(38, 38, 38);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(tl('diagnosis'), 14, finalY + 28);
    doc.setFont("helvetica", "normal");
    const diagLines = doc.splitTextToSize(data.diagnosis, pageW - 28);
    doc.text(diagLines, 14, finalY + 34);
  }

  // Notes
  if (data.notes) {
    const notesY = data.diagnosis ? finalY + 46 : finalY + 28;
    doc.setTextColor(38, 38, 38);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(tl('notes'), 14, notesY);
    doc.setFont("helvetica", "normal");
    const noteLines = doc.splitTextToSize(data.notes, pageW - 28);
    doc.text(noteLines, 14, notesY + 6);
  }

  // Watermark for FREE plan only
  if (isFree) {
    doc.setTextColor(200, 200, 200);
    doc.setFontSize(50);
    doc.setFont("helvetica", "bold");
    const centerX = pageW / 2;
    const centerY = doc.internal.pageSize.getHeight() / 2;
    doc.saveGraphicsState();
    doc.text("GarageFlow FREE", centerX, centerY, {
      align: "center",
      angle: 45,
    });
    doc.restoreGraphicsState();
  }

  // Legal disclaimer
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFillColor(245, 245, 245);
  doc.rect(14, pageH - 28, pageW - 28, 12, 'F');
  doc.setTextColor(120, 120, 120);
  doc.setFontSize(6);
  doc.setFont("helvetica", "italic");
  doc.text(tl('disclaimer'), pageW / 2, pageH - 22, { align: "center" });

  // Footer
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(7);
  
  if (isFree) {
    // FREE: footer includes GarageFlow branding
    const footerParts = [`${data.shopName} — Powered by GarageFlow`];
    if (data.shopNif) footerParts.push(`NIF: ${data.shopNif}`);
    if (data.shopAddress) footerParts.push(data.shopAddress);
    doc.text(footerParts.join(' | '), pageW / 2, pageH - 8, { align: "center" });
  } else {
    // PRO/GARAGE: only shop info, no GarageFlow
    const footerParts = [data.shopName];
    if (data.shopNif) footerParts.push(`NIF: ${data.shopNif}`);
    if (data.shopAddress) footerParts.push(data.shopAddress);
    doc.text(footerParts.join(' | '), pageW / 2, pageH - 8, { align: "center" });
  }

  return doc;
}

export function exportToCsv(data: any[], filename: string) {
  if (data.length === 0) return;
  const headers = Object.keys(data[0]);
  const csvRows = [
    headers.join(';'),
    ...data.map(row => headers.map(h => {
      const val = row[h];
      if (val === null || val === undefined) return '';
      if (typeof val === 'object') return JSON.stringify(val);
      return String(val).replace(/;/g, ',');
    }).join(';'))
  ];
  const blob = new Blob(['\uFEFF' + csvRows.join('\n')], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}
