// deno-lint-ignore-file no-explicit-any
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";
import { buildChildInviteEmail } from "../_shared/child-invite-email.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

/**
 * invite-child-shop
 * ------------------------------------------------------------------
 * Called by an authenticated Oficina Mãe to create a child shop with an
 * independent auth account. The auth action link is generated by the backend,
 * but the email itself is sent through the branded GarageFlow sender only.
 */

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const REDIRECT_URL =
  Deno.env.get("CHILD_SHOP_INVITE_REDIRECT") ??
  "https://garageflow-pt.lovable.app/reset-password?realm=erp";

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization") ?? "";
    if (!authHeader.startsWith("Bearer ")) {
      return json({ error: "NOT_AUTHENTICATED" }, 401);
    }

    const userClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      global: { headers: { Authorization: authHeader } },
    });
    const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false },
    });

    const { data: userRes, error: userErr } = await userClient.auth.getUser();
    if (userErr || !userRes.user) return json({ error: "NOT_AUTHENTICATED" }, 401);
    const caller = userRes.user;

    const body = await req.json().catch(() => ({}));
    const name = String(body?.name ?? "").trim();
    const email = String(body?.email ?? "").trim().toLowerCase();
    if (!name) return json({ error: "MISSING_NAME" }, 400);
    if (!email || !/^\S+@\S+\.\S+$/.test(email)) {
      return json({ error: "INVALID_EMAIL" }, 400);
    }

    const { data: mother } = await admin
      .from("shops")
      .select("id, country, currency, country_code, timezone, language, vat_rate, labor_rate")
      .eq("group_owner_id", caller.id)
      .eq("user_id", caller.id)
      .order("created_at", { ascending: true })
      .limit(1)
      .maybeSingle();

    if (!mother) return json({ error: "NOT_GROUP_OWNER" }, 403);

    const { data: status } = await admin.rpc("get_shop_creation_status", {
      _user_id: caller.id,
    });
    if (!status?.allowed) {
      return json({ error: "SHOP_LIMIT_REACHED", status }, 403);
    }

    const link = await createPasswordActionLink(admin, email, name, "invite");
    let childUserId = link.userId;
    let authEmailMode: "invite" | "recovery" = link.mode;

    if (!childUserId) return json({ error: "INVITE_FAILED" }, 500);

    await admin.auth.admin.updateUserById(childUserId, {
      user_metadata: {
        source: "child_shop_invite",
        skip_shop_creation: "true",
        account_type: "garage_child",
        shop_name: name,
      },
    }).catch(() => null);

    const { data: existingChildShops } = await admin
      .from("shops")
      .select("id, user_id, group_owner_id")
      .eq("user_id", childUserId);

    const existingInThisGroup = (existingChildShops ?? []).find((s: any) => s.group_owner_id === caller.id && s.user_id !== caller.id);
    const ownsIndependentWorkshop = (existingChildShops ?? []).some((s: any) => s.group_owner_id === childUserId);
    const belongsToOtherGroup = (existingChildShops ?? []).some((s: any) => s.group_owner_id !== caller.id && s.group_owner_id !== childUserId);

    if (ownsIndependentWorkshop || belongsToOtherGroup) {
      return json({ error: "EMAIL_ALREADY_HAS_WORKSHOP" }, 409);
    }

    if (existingInThisGroup?.id) {
      const emailResult = await sendBrandedPasswordEmail({
        to: email,
        recipientName: name,
        language: mother?.language,
        actionLink: link.actionLink,
      });
      if (!emailResult.ok) {
        return json({ error: "BRANDED_EMAIL_FAILED", detail: emailResult.detail }, 502);
      }
      return json({ ok: true, shop_id: existingInThisGroup.id, user_id: childUserId, auth_email: authEmailMode, email_id: emailResult.emailId }, 200);
    }

    const { data: shop, error: insertErr } = await admin
      .from("shops")
      .insert({
        user_id: childUserId,
        group_owner_id: caller.id,
        name,
        email,
        country: mother?.country ?? "Portugal",
        country_code: mother?.country_code ?? "PT",
        currency: mother?.currency ?? "EUR",
        timezone: mother?.timezone ?? "Europe/Lisbon",
        language: mother?.language ?? "pt",
        vat_rate: mother?.vat_rate ?? 23,
        labor_rate: mother?.labor_rate ?? 35,
      })
      .select("id")
      .single();

    if (insertErr) {
      return json({ error: "SHOP_INSERT_FAILED", detail: insertErr.message }, 500);
    }

    await admin
      .from("shop_users")
      .upsert(
        { shop_id: shop.id, user_id: childUserId, role: "owner" },
        { onConflict: "shop_id,user_id" },
      );

    const emailResult = await sendBrandedPasswordEmail({
      to: email,
      recipientName: name,
      language: mother?.language,
      actionLink: link.actionLink,
    });
    if (!emailResult.ok) {
      return json({ error: "BRANDED_EMAIL_FAILED", detail: emailResult.detail }, 502);
    }

    return json({ ok: true, shop_id: shop.id, user_id: childUserId, auth_email: authEmailMode, email_id: emailResult.emailId }, 200);
  } catch (e: any) {
    return json({ error: "UNEXPECTED", detail: String(e?.message ?? e) }, 500);
  }
});

function json(body: unknown, status: number) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

async function findUserIdByEmail(admin: any, email: string): Promise<string | null> {
  for (let page = 1; page <= 20; page += 1) {
    const { data, error } = await admin.auth.admin.listUsers({ page, perPage: 1000 });
    if (error) return null;
    const match = data?.users?.find((u: any) => String(u.email ?? "").toLowerCase() === email);
    if (match?.id) return match.id;
    if (!data?.users || data.users.length < 1000) break;
  }
  return null;
}

async function createPasswordActionLink(
  admin: any,
  email: string,
  shopName: string,
  preferred: "invite" | "recovery",
): Promise<{ userId: string | null; actionLink: string; mode: "invite" | "recovery" }> {
  const options = {
    redirectTo: REDIRECT_URL,
    data: {
      source: "child_shop_invite",
      skip_shop_creation: "true",
      account_type: "garage_child",
      shop_name: shopName,
    },
  };

  const invite = preferred === "invite"
    ? await admin.auth.admin.generateLink({ type: "invite", email, options })
    : null;

  if (invite && !invite.error) {
    const actionLink = String(invite.data?.properties?.action_link ?? "");
    return { userId: invite.data?.user?.id ?? null, actionLink, mode: "invite" };
  }

  const inviteMsg = String(invite?.error?.message || "").toLowerCase();
  if (invite && !inviteMsg.includes("already") && !inviteMsg.includes("registered") && !inviteMsg.includes("exists")) {
    throw new Error(`INVITE_LINK_FAILED: ${invite.error?.message}`);
  }

  const userId = await findUserIdByEmail(admin, email);
  if (!userId) throw new Error("USER_LOOKUP_FAILED");

  const recovery = await admin.auth.admin.generateLink({
    type: "recovery",
    email,
    options: { redirectTo: REDIRECT_URL },
  });
  if (recovery.error) throw new Error(`RECOVERY_LINK_FAILED: ${recovery.error.message}`);

  return {
    userId,
    actionLink: String(recovery.data?.properties?.action_link ?? ""),
    mode: "recovery",
  };
}

async function sendBrandedPasswordEmail(params: {
  to: string;
  recipientName: string;
  language?: string | null;
  actionLink: string;
}): Promise<{ ok: true; emailId?: string } | { ok: false; detail: string }> {
  if (!params.actionLink) return { ok: false, detail: "MISSING_ACTION_LINK" };

  const copy = buildChildInviteEmail({ recipientName: params.recipientName, language: params.language });
  const response = await fetch(`${SUPABASE_URL}/functions/v1/send-email`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${SERVICE_ROLE_KEY}`,
      "x-internal-token": SERVICE_ROLE_KEY,
    },
    body: JSON.stringify({
      to: params.to,
      from: "GarageFlow <noreply@garageflow.pt>",
      subject: copy.subject,
      html: copy.html,
      branded: true,
      brand: "garageflow",
      preheader: copy.preheader,
      cta: { label: copy.ctaLabel, url: params.actionLink },
      footerNote: copy.footerNote,
      emailType: "child_shop_invite",
    }),
  });

  const text = await response.text();
  let parsed: any = null;
  try { parsed = text ? JSON.parse(text) : null; } catch { /* keep raw text */ }
  if (!response.ok) {
    return { ok: false, detail: parsed?.error || parsed?.detail || text || `HTTP_${response.status}` };
  }
  return { ok: true, emailId: parsed?.email_id || parsed?.data?.id };
}