// This file is automatically generated. Do not edit it directly.
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getRealmClient } from './realmClients';

type ClientKey = keyof SupabaseClient<Database>;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_target, prop: ClientKey) {
    return getRealmClient()[prop];
  },
});